# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'minitest'
gem 'pry'
gem 'pry-doc'
gem 'ruby_parser'
gem 'rubocop'
gem 'seeing_is_believing'
gem 'solargraph'
